---
- hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: "{{ apache_package }}"
        update_cache: true
        state: latest 
      when: ansible_facts['os_family'] == "Debian"
      notify: start apache service
    - name: install apache2
      yum:
        name: "{{ httpd_package }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      notify: start httpd service
    - name: copy file 
      template: 
        src:  "/home/ansible/playbooks/index.html"
        dest:  "/var/www/html/index.html"
  handlers:
    - name: start apache service
      service: 
        name: "{{ apache_package }}"
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "Debian"
    - name: start httpd services
      service: 
        name: "{{ httpd_package }}"
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "RedHat"