hosts: all 
become: yes
tasks:
  - name: install apache2
    yum:
      name: httpd
      state: present
  - name: install php
    user: 
      name: "{{ item }}"
      state: present
    with_items:
      - php 
      - libapache2-mod-php 
      - php-mysql
  - name: copy file 
    template: 
      src:  "/home/ansible/playbooks/index.html"
      dest:  "/var/www/html/index.html"
  - name: copy php 
    template:
      src: "/home/ansible/playbooks/info.php"
      dest: nano /var/www/html/info.php
  - name: start services
    service: 
      name: httpd
      enabled: yes
      state: restarted