---
- hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        update_cache: true
        state: latest 
    - name: start serrvice
      service: 
        name: apache2
        enabled: yes
        state: restarted
---
hosts: all 
become: yes
tasks:
  - name: install apache2
    yum:
      name: httpd
      state: present
  - name: copy file 
    template: 
      src:  "/home/ansible/playbooks/index.html"
      dest:  "/var/www/html/index.html"
  - name: start services
    service: 
      name: httpd
      enabled: yes
      state: restarted
---
- hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        update_cache: true
        state: latest 
      when: ansible_facts['os_family'] == "Debian"
      
    - name: install apache2
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: copy file 
      template: 
        src:  "/home/ansible/playbooks/index.html"
        dest:  "/var/www/html/index.html"

    - name: start service
      service: 
        name: apache2
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "Debian"
    - name: start services
      service: 
        name: httpd
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "RedHat"
---
- hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt: 
        name: apache2
        update_cache: true
        state: latest 
      when: ansible_facts['os_family'] == "Debian"
      notify: start apache service
    - name: install apache2
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      notify: start httpd service
    - name: copy file 
      template: 
        src:  "/home/ansible/playbooks/index.html"
        dest:  "/var/www/html/index.html"
  handlers:
    - name: start apache service
      service: 
        name: apache2
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "Debian"
    - name: start httpd services
      service: 
        name: httpd
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "RedHat"