- hosts: all
  become: yes
  tasks: 
    - name: fail for other platforms
      fail: 
        msg: "this platform is developed only for ubuntu"
      when: 
      - ansible_os_family != "Debian" 
        
    - name: install apache2
      apt: 
        name: apache2
        update_cache: true
        state: latest 
    - name: start serrvice
      service: 
        name: apache2
        enabled: yes
        state: restarted