- name: install nopcommerse application
  hosts: all
  become: yes
  tasks: 
  - name: install nopcommerse
    get_url:
     url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
     dest: /usr/local/
  - name: install softwates
    apt: 
      name: apt-transport-https
      update_cache: yes
      state: present
  - name: install softwates
    apt: 
      name: aspnetcore-runtime-5.0
      update_cache: yes
      state: present
  - name: change file permissions
    file:
        path: /var/www/shop.example.com/
        owner: ansible
        group: ansible
        state: directory
        recurse: yes
        mode: '1777'
  - name: install nopcommerse
    get_url:
     url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
     dest: /var/www/shop.example.com/
  - name: untar tomcat
    unarchive:
        src: nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/shop.example.com/
        remote_src: yes
  - name: copy conf file
    template: 
        src: /nop.conf
        dest: /etc/nginx/sites-available/shop.example.com.conf
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
  - name: start services
    shell: nohup /usr/local//bin/startup.sh